portal/templates/academy/student/unit_list.html
Default to instructor's username in student unit list when name is missing (issue #17 ).
=> Default to instructor's username in student unit list

portal/hackathons/views.py
=> Duplicate entries in instructors hackathon admin view

portal/academy/views.py, portal/templates/hackathons/instructor/hackathon_admin.html
=> hackathon confirmation messages and ordering learning units

portal/hackathons/views.py, portal/templates/hackathons/instructor/hackathon_admin.html
=> Delete test submissions as a manual step

portal/hackathons/services.py, portal/hackathons/views.py
=> Only pass data validation errors to students

portal/academy/admin.py
=> Add created time to admin grade listing

portal/academy/views.py, portal/templates/academy/instructor/user_list.html
=> solves #28 | On the instructor grade listing add date of submission

portal/templates/academy/common/unit_detail.html
The issue is detailed in #20 and the width of the description of the LU is not fixed, leading to a long line without breaks. 
Added a specific width limit and justified text
=> #20 - Lu description size width limit

portal/templates/candidate_templates/slu.html
I can't run the portal locally.
When reviewing could you make sure that the changes look good? 😇
=> Update assignments setup instructions

portal/staff/domain.py
closes https://github.com/LDSSA/portal/issues/115
=> submitting for review

README.md, config/settings/test.py, config/urls.py, docker-compose.yml, portal/admissions/urls.py, portal/candidate/tests/test_domain.py, portal/conftest.py, portal/users/tests/factories.py, portal/users/tests/test_forms.py, portal/users/tests/test_models.py, portal/users/tests/test_urls.py, portal/users/tests/test_views.py
Run through (also in README of this branch):
```
docker-compose run tests
```
Results:
An amazing 4 tests running 🎉🎉
=> [133] Make tests great again: step 1 - bring testing back

portal/academy/tests/tests.py, portal/academy/urls.py, portal/academy/views.py, portal/templates/academy/instructor/user_list.html
Closes #146 
Instructors user view:
* Order learning units by code besides submisison data
* Order users by name
* Add a scrollbar
=> Instructor views improvements

README.md, portal/users/management/commands/_create_user.py, portal/users/management/commands/create-instructor.py, portal/users/management/commands/create-student.py
From README:
> Create an instructor:
> 
> ```
> ./manage.py create-instructor \
>   -u 'ana' \
>   -p 'ana1234' \
>   -e 'ana@lisbondatascience.org' \
>   -n 'Ana' \
>   -git 'Ana' \
>   -s 'U21392ANA' \
>   -g 'female' \
>   -t 'regular' \
> ```
> 
> Create a student:
> 
> ```
> ./manage.py create-student \
>   -u 'joao' \
>   -p 'joao1234' \
>   -e 'joao@lisbondatascience.org' \
>   -n 'Joao' \
>   -git 'Joao' \
>   -s 'U21392JOAO' \
>   -g 'male' \
>   -t 'regular' \
> ```
> 
* Create instructor:
* Create student:
You can see the outcome of the user creation in the admin:
Or you can login with these users (as we skipped email validation):
Closes #87
=> [87] Add django management commands for user and instructor

README.md, portal/academy/management/commands/create-spec.py, portal/academy/management/commands/create-unit.py
From readme:
> Create a specialization:
> ```
> docker-compose run --rm django ./manage.py create-spec \
>   -c S01 \
>   -n 'Bootcamp'
> ```
> 
> Create a unit:
> 
> ```
> docker-compose run --rm django ./manage.py create-unit \
>   -s S01 \
>   -c SLU01 \
>   -n 'SLU01 - Pandas' \
>   -due '2020-04-10' \
>   --open
> ```
If everything goes well you should see:
If the unit or spec already exists:
=> [87] Add django management commands for specializations and units

README.md, portal/academy/management/commands/create-spec.py, scripts/db_seed.sh
This MR introduces a script to seed the database for functionally testing portal locally. This doesn't fix the fixtures but it means to replace them
From the README:
> To seed the entire db with pre-arranged data, run:
> 
> ```
> docker-compose run --rm django ./scripts/db_seed.sh
> ```
> 
> You can then login with any of the users created, for which the passwords are `<user>1234` or 
> with the admin (user `admin`, password `123`)
Login with student:
Login with instructor:
=> [88] Add script to seed the db, replacing features

portal/hackathons/services.py, portal/hackathons/views.py
Changes submission issues to ValidationError.
Always displays submission error to students.
Fixes PORTAL-76
Fixes PORTAL-72
=> Hackathon submission handling improvements

.gitignore, portal/academy/tests/test_views.py
* Rename tests to prepare for multiple test files
* Add pycharm `.idea` to gitignore
* Add docstring to csvdata test
=> [149] Cleanup and run academy module tests

portal/academy/services.py, portal/academy/tests/test_services.py, portal/conftest.py
Task 1 of proposal in https://github.com/LDSSA/portal/issues/149
Adds service to compute graduation eligibility from attendances. Implements the rule that a student can graduate if:
- they have missed at most one hackathon
- they haven't missed the first hackathon
As of now the function is still not called, only introduced with proper testing. On a later PR it will be used to 
set a flag `can_graduate` in the Student, as stated in the plan
=> [149] Add service to compute graduation eligibility

portal/academy/serializers.py, portal/academy/views.py, portal/templates/academy/instructor/user_list.html, portal/users/admin.py
* By eligible students:
* By non-eligible students:
=> [173] Add can graduate filter on instructor student list

portal/templates/candidate_templates/home.html, portal/templates/candidate_templates/scholarship.html, portal/templates/candidate_templates/slu.html
=> update copy for batch 6

portal/templates/candidate_templates/code_of_conduct.html
in compliance with https://ldssa.github.io/wiki/Starters%20Academy%20(LDSSA)/07-Refund-Policy/
=> Update refund policy

portal/grading/services.py
tries to fix https://sentry.io/organizations/ldsa/issues/3318164065/?project=1450635&query=is%3Aunresolved
=> async grading

portal/grading/services.py
continuation of https://github.com/LDSSA/portal/pull/231
=> assync grading

config/settings/settings.py, docker/production/django/Dockerfile, docs/setup.rst, portal/grading/services.py
https://github.com/LDSSA/portal/issues/241
=> Add batch name variable

portal/staff/views.py, portal/templates/staff_templates/payment_id.html
=> [235] Fix reset payment info

docker/local/django/Dockerfile, docs/running.rst, portal/applications/models.py, portal/selection/models.py
Closes #130 
- Changed `Selection` to allow for blank values in Admin page
- Changed `Application` to allow for blank values in Admin page
- Changed docker image to python3.8
- Fixed document
=> [130] Null application selection

config/settings/settings.py, portal/users/admin.py
=> Add graduation eligibility to admin view

.envs/.local/.django, portal/users/admin.py
=> Fix Issue 203

docs/backup.rst
adds documentation on how to back up the portal and links to existing backups
=> Portal backup

.circleci/config.yml
- Removed `deploy` and `sentry` stages in the Circle CI since they were not being used.
=> Refactor: circle ci config

.readthedocs.yaml
=> [#266] Fix: Remove linkcheck job from the readthedocs config

manage.py
- Manage.py was not loading due to not calling the `resolve` method.
=> Bugfix: str not method

portal/templates/candidate_templates/scholarship.html
- The student fee is getting back to pre-covid price, which is half the normal price.
=> Update: student fee

portal/candidate/urls.py, portal/candidate/views.py, portal/templates/candidate_templates/before_coding_test.html, portal/templates/candidate_templates/coding_test.html, portal/templates/candidate_templates/confirmation_coding_test.html, portal/templates/candidate_templates/home.html, portal/templates/candidate_templates/slu.html
- Formatting changes in home, slu, coding_test and before_coding_test to make things clearer and simpler.
- Added another page confirmation_coding_test. This should go between before_coding_test and coding_test. I don't know how to make this happen, so if you can do it or give me pointers. Thank you very much!
=> Updating for the admissions

.gitignore, deploy/ldsa-portal/.helmignore, deploy/ldsa-portal/Chart.lock, deploy/ldsa-portal/Chart.yaml, deploy/ldsa-portal/templates/NOTES.txt, deploy/ldsa-portal/templates/_helpers.tpl, deploy/ldsa-portal/templates/deployment.yaml, deploy/ldsa-portal/templates/hpa.yaml, deploy/ldsa-portal/templates/ingress.yaml, deploy/ldsa-portal/templates/letsencrypt.yaml, deploy/ldsa-portal/templates/service.yaml, deploy/ldsa-portal/templates/serviceaccount.yaml, deploy/ldsa-portal/templates/tests/test-connection.yaml, deploy/ldsa-portal/values.yaml
- Add valid `helm` charts to the portal
- #
=> Feature: create valid helm files

deploy/ldsa-portal/templates/django-configmap.yaml, deploy/ldsa-portal/values.yaml, portal/ci.env, portal/config/settings/settings.py, portal/local.env, portal/portal/grading/services.py
- No need for batch name in docker image anymore. We will only separate the `dev` and `prod` images.
- #
=> Feature: make dev portal use dev docker images

CHANGELOG, portal/portal/academy/views.py, portal/portal/grading/services.py, portal/portal/templates/academy/common/unit_detail.html, portal/pyproject.toml
- Adding message after clicking the Grade button in the unit list.
- Creating the `GRADING_USER` and a Token if it doesn't exist yet.
- #
=> Release: v0.2.1

deploy/ldsa-portal/templates/django-configmap.yaml
=> hotfix: change student batch repo name

.github/workflows/deployment.yml
=> Setting correct host with https

portal/portal/hackathons/admin.py
- Make it easier to change hackathon teams in the admin page
=> Feature: make it easier to change users in a team

CHANGELOG, portal/config/settings/settings.py, portal/poetry.lock, portal/portal/users/adapters.py, portal/pyproject.toml
- Fixed the password reset view to not validate the email address.
- Improve Team Admin page to make it easier to adjust the team members.
=> Release: v0.2.3

portal/portal/templates/candidate_templates/home.html
- Simplify text on home page and add some info.
- # Not resolving any issue
=> Change text on home page

portal/portal/templates/candidate_templates/home.html
- Admissions home page formatting.
- Not solving any issue.
=> Format the home page text.

portal/portal/templates/account/signup.html, portal/portal/templates/candidate_templates/home.html
- change formatting
- does not solve any issue
=> Format admissions pages

portal/portal/templates/account/signup.html, portal/portal/templates/candidate_templates/home.html
- formatting for admissions pages
- does not solve any issue
=> Formatting for admissions pages

portal/portal/templates/candidate_templates/home.html
- Format admissions page
- none
=> Format admissions page

portal/portal/candidate/views.py, portal/portal/templates/candidate_templates/before_coding_test.html, portal/portal/templates/candidate_templates/home.html, portal/portal/templates/candidate_templates/slu.html
- Repair admissions part on the homepage
- None
=> Repair home page

portal/portal/applications/domain.py
- Correct status from admissions-applications to admissions
- None
=> Correct submission open criterium

portal/portal/templates/candidate_templates/slu.html
- in slu template, enable the submit button permanently
- None
=> Workaround for submit button

portal/portal/applications/domain.py, portal/portal/templates/candidate_templates/slu.html
=> Admissions 2025

portal/portal/grading/services.py
- Change image name for grading
- None
=> Repair submissions

portal/portal/grading/services.py
- Change admissions docker name
- None
=> Change docker name

portal/portal/templates/base.html
- Add home link to base html template
-
=> Add home url to base page

portal/config/settings/settings.py, portal/portal/scheduler/management/commands/run-scheduler.py
- Change default academy and admission dates and disable automatic switching to academy portal status in the scheduler.
- None
=> Circumvent scheduler

portal/bin/start_dev.sh
- Correct command to run scheduler
- None
=> Add scheduler run after portal start

portal/config/settings/settings.py
- Correct datetime definition
- None
=> Add timezone info to datetime definition

portal/config/settings/settings.py, portal/portal/scheduler/management/commands/run-scheduler.py
=> Complete datetime

portal/config/settings/settings.py
=> Correct default start dates

portal/portal/staff/views.py
- Disable date checks temporarily
- None
=> Disable check temporarily

portal/portal/staff/views.py
- Repair type of academy start date
- None
=> Repair academy start date

portal/portal/staff/views.py
- Put everything back and add scheduler run after portal start
- None
=> Put everything back

portal/bin/start_dev.sh
- Change dev portal start script
- None
=> Start scheduler before portal

portal/config/settings/settings.py, portal/portal/academy/models.py, portal/portal/applications/migrations/0004_auto_20200301_1823.py, portal/portal/scheduler/management/commands/run-scheduler.py, portal/portal/staff/views.py, portal/portal/users/adapters.py, portal/tests/academy/test_academy_views.py
- Correct start date types
- None
=> Correct types

portal/config/settings/settings.py, portal/portal/academy/models.py
- Change back default value of due_date
-
=> Change default value back

portal/portal/scheduler/management/commands/run-scheduler.py
=> Initial portal status

portal/portal/templates/candidate_templates/slu.html
=> Submit warning

portal/portal/admissions/emails.py, portal/portal/templates/candidate_templates/coding_test.html, portal/portal/templates/candidate_templates/home.html
- Add info about second applications round in the failed email
- Add a second time counter on the coding test page
- Add coding test tips
- None
=> Change failed email

portal/portal/templates/candidate_templates/home.html
- Add info about admission test on the homepage before the applications start
- None
=> Add info about admission test

portal/portal/templates/candidate_templates/home.html
- Add info about second round to the failed student homepage
- None
=> Add info about second round

portal/portal/templates/candidate_templates/home.html
- Show candidate selection status
- None
=> Change candidate homepage

portal/portal/templates/candidate_templates/home.html
=> Remove endif

portal/portal/templates/candidate_templates/home.html
=> Correct if

portal/portal/applications/models.py, portal/portal/templates/candidate_templates/coding_test.html, portal/portal/templates/candidate_templates/home.html
- Add success message for candidates with passed status
- None
=> Admissions selection

.github/workflows/portal-tests.yml, portal/portal/staff/domain.py, portal/portal/templates/candidate_templates/home.html, portal/portal/templates/staff_templates/events.html
- Try to see application records from database
- None
=> See applications

portal/portal/staff/domain.py
- Reset email sent status
- None
=> Selection status

portal/portal/admissions/emails.py, portal/portal/staff/domain.py
- WIP - modifying 'applications over' event
- None
=> See selection emails

portal/portal/applications/domain.py, portal/portal/staff/domain.py
- Modify 'applications over' event for wave 2
- None
=> applications over event

portal/portal/templates/candidate_templates/home.html
- Correct batch8 to batch9
- None
=> Correct student repo name

portal/portal/templates/candidate_templates/home.html
- Update student repo name in the django-config file
- None
=> Update student repo name

deploy/ldsa-portal/templates/django-configmap.yaml, portal/ci.env, portal/local.env, portal/portal/academy/models.py
=> Correct syntax error

portal/portal/academy/views.py, portal/portal/staff/export.py
- Add academy_type_preference to the exported csv file
- None
=> Export academy type
